src/Entity/Contact.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource ;
use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource(attributes={"pagination_enabled"=false})
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tele;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse_pa;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typePanne;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getTele(): ?string
    {
        return $this->Tele;
    }

    public function setTele(string $Tele): self
    {
        $this->Tele = $Tele;

        return $this;
    }

    public function getAdressePa(): ?string
    {
        return $this->Adresse_pa;
    }

    public function setAdressePa(string $Adresse_pa): self
    {
        $this->Adresse_pa = $Adresse_pa;

        return $this;
    }

    public function getTypePanne(): ?string
    {
        return $this->typePanne;
    }

    public function setTypePanne(string $typePanne): self
    {
        $this->typePanne = $typePanne;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;


use App\Entity\Panneaux;
use App\Form\PanneauxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Repository\PanneauxRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SearchController extends AbstractController
{
    /**
     * @Route("/search", name="app_search")
     */
    public function index(): Response
    {
        return $this->render('search/index.html.twig', [
            'controller_name' => 'SearchController',
        ]);
    }
/**
     * @Route("/searcha", name="app_search")
     */
public function searchBar()
    {
        $form = $this->createFormBuilder()
            ->setAction($this->generateUrl('handleSearch'))
            ->add('query', EntityType::class, [
                'class' => Panneaux::class,
                'choice_label' => 'NomPa',
                'placeholder' => 'Panneaux',
                'label' => 'Panneaux',
                'attr' => [
                    'class' => 'select-tag'
                ],
            
                
            ])
            ->add('recherche', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
            ->getForm();
        return $this->render('search/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/handleSearch", name="handleSearch")
     * @param Request $request
     */
    public function handleSearch(Request $request,PanneauxRepository $panneauxRepository)
    {
        $query = $request->request->get('form')['query'];
        if($query) {
            $panneauxes = $panneauxRepository->findPanneauxByName($query);
        }
        return $this->render('Panneaux/index.html.twig', [
            'panneauxes' => $panneauxes,
             
        ]);
    }
}

templates/search/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SearchController!{% endblock %}

{% block body %}
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <style>
        .modal .select-tag {
            
            width : 509px;
        }
        </style>

<div class="example-wrapper">
  

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/ticket/ticket/src/Controller/SearchController.php'|file_link(0) }}">src/Controller/SearchController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/ticket/ticket/templates/search/index.html.twig'|file_link(0) }}">templates/search/index.html.twig</a></code></li>
    </ul>
    {{ form(form) }}
    {% if app.request.method == 'POST' %}
    <div>
        {% if panneaux | length == 0 %}
            <h4>Aucun résulat pour votre recherche.</h4>
           {% else %}
               <h3 class="mt-3">Vos résulats de recherche :</h3>
               {% for panneaux in panneauxes %}
                   <div class="mt-3 p-3 bg-light border rounded">
                       <a href="{{ path('app_panneaux_index') }}">
                              <h6 class="text-dark"><i class="bi bi-arrow-down-right-square-fill text-primary"></i> {{ Panneaux.adressePa }}</h6>
                              
                       </a>
                   </div>
              {% endfor %}
          {% endif %}
     </div>
{% endif %}
</div>
{% endblock %}
 {% block javascripts %}
                    {{ encore_entry_script_tags('app') }}
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
                    <script>
                    
                    $(function(){
                       
                    $('.select-tag').select2();
    });
     
                    
                    </script>
                    
                {% endblock %}